# Generated by Django 4.1 on 2022-08-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store_api', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='date_order',
        ),
    ]
