# Generated by Django 4.1 on 2022-08-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_api', '0004_rename_date_order_date_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='products', to='Store_api.product'),
        ),
    ]
